services:
  - type: web
    name: mafia-nights-server
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8080
    healthCheckPath: /health
